-- TESTBENCH PARA PWM SSDM CON LFSR

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY TB_PWM_SSDM_LFSR IS
END TB_PWM_SSDM_LFSR;

ARCHITECTURE TB OF TB_PWM_SSDM_LFSR IS

	-- CONSTANTES DE CONFIGURACIÓN
	CONSTANT TBPERIOD : TIME := 10 NS; -- RELOJ DE 100MHZ
	CONSTANT G_WIDTH : INTEGER := 8;  -- (8 BITS => 2^8 = 256 COLORES)

	-- DECLARACIÓN DEL COMPONENTE A TESTEAR
	COMPONENT PWM_SSDM_LFSR
		GENERIC (
			G_WIDTH : INTEGER := 8
		);
		PORT (
			CLK_PWM : IN  STD_LOGIC;
			RST : IN  STD_LOGIC;
			DUTY_CYCLE_IN : IN  STD_LOGIC_VECTOR (G_WIDTH-1 DOWNTO 0);
			PWM_OUT : OUT STD_LOGIC
		);
	END COMPONENT;

	-- SEÑALES DE CONEXIÓN (CON VALORES INICIALES)
	SIGNAL CLK_PWM : STD_LOGIC := '0';
	SIGNAL RST : STD_LOGIC := '0';
	SIGNAL DUTY_CYCLE_IN : STD_LOGIC_VECTOR (G_WIDTH-1 DOWNTO 0) := (OTHERS => '0');
	SIGNAL PWM_OUT : STD_LOGIC;
	SIGNAL TBSIMENDED : STD_LOGIC := '0';

BEGIN

	-- INSTANCIACIÓN DEL DUT
	DUT : PWM_SSDM_LFSR
	GENERIC MAP (
		G_WIDTH => G_WIDTH
	)
	PORT MAP (
		CLK_PWM => CLK_PWM,
		RST => RST,
		DUTY_CYCLE_IN => DUTY_CYCLE_IN,
		PWM_OUT => PWM_OUT
	);

	-- GENERACIÓN DEL RELOJ
	CLK_PWM <= NOT CLK_PWM AFTER TBPERIOD/2 WHEN TBSIMENDED /= '1' ELSE '0';

	-- PROCESO DE ESTÍMULOS
	STIMULI : PROCESS
	BEGIN
		-- INICIALIZACIÓN Y RESET
		DUTY_CYCLE_IN <= (OTHERS => '0');
		RST <= '1';
		WAIT FOR 100 NS;
		RST <= '0';
		WAIT FOR 100 NS;

		-- PRUEBA BRILLO BAJO (10%)
		-- VALOR: 25 DE 255
		DUTY_CYCLE_IN <= STD_LOGIC_VECTOR(TO_UNSIGNED(25, G_WIDTH));
		WAIT FOR 100 * TBPERIOD;

		-- PRUEBA BRILLO MEDIO (50%)
		-- VALOR: 128 DE 255
		DUTY_CYCLE_IN <= STD_LOGIC_VECTOR(TO_UNSIGNED(128, G_WIDTH));
		WAIT FOR 100 * TBPERIOD;

		-- PRUEBA BRILLO ALTO (90%)
		-- VALOR: 230 DE 255
		DUTY_CYCLE_IN <= STD_LOGIC_VECTOR(TO_UNSIGNED(230, G_WIDTH));
		WAIT FOR 100 * TBPERIOD;

		-- PRUEBA LÍMITE (100%)
		-- DEBERÍA ESTAR CASI SIEMPRE A '1'
		DUTY_CYCLE_IN <= (OTHERS => '1');
		WAIT FOR 100 * TBPERIOD;

		-- FINAL DE LA SIMULACIÓN
		WAIT FOR 50 * TBPERIOD;
		ASSERT FALSE REPORT "SIMULACION PWM SSDM LFSR FINALIZADA OK" SEVERITY NOTE;
		TBSIMENDED <= '1';
		WAIT;
	END PROCESS;

END TB;