LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

USE WORK.PKG_RGB_TYPES.ALL;

ENTITY TB_RGB_CONTROLADOR IS
END TB_RGB_CONTROLADOR;

ARCHITECTURE TB OF TB_RGB_CONTROLADOR IS

	CONSTANT TBPERIOD : TIME := 100 NS;

	CONSTANT ROJO_SW  : STD_LOGIC_VECTOR(3 DOWNTO 0) := "0100";
	CONSTANT VERDE_SW : STD_LOGIC_VECTOR(3 DOWNTO 0) := "0010";
	CONSTANT AZUL_SW  : STD_LOGIC_VECTOR(3 DOWNTO 0) := "0001";

	COMPONENT RGB_CONTROLADOR
		PORT (
			CLK_RGB      : IN  STD_LOGIC;
			RST_RGB      : IN  STD_LOGIC;
			BTN_UP       : IN  STD_LOGIC;
			BTN_DOWN     : IN  STD_LOGIC;
			SW_RGB       : IN  STD_LOGIC_VECTOR (3 DOWNTO 0);
			VALOR_SALIDA : OUT T_COLORES_RGB
		);
	END COMPONENT;

	SIGNAL CLK_RGB    : STD_LOGIC := '0';
	SIGNAL RST_RGB    : STD_LOGIC := '0';
	SIGNAL BTN_UP     : STD_LOGIC := '0';
	SIGNAL BTN_DOWN   : STD_LOGIC := '0';
	SIGNAL SW_RGB     : STD_LOGIC_VECTOR (3 DOWNTO 0) := "0000";
	SIGNAL SIM_END    : STD_LOGIC := '0';

	SIGNAL S_VALOR_SALIDA : T_COLORES_RGB;
	SIGNAL ROJO_OUT  : STD_LOGIC_VECTOR(3 DOWNTO 0);
	SIGNAL VERDE_OUT : STD_LOGIC_VECTOR(3 DOWNTO 0);
	SIGNAL AZUL_OUT  : STD_LOGIC_VECTOR(3 DOWNTO 0);

BEGIN

	DUT : RGB_CONTROLADOR
	PORT MAP (
		CLK_RGB      => CLK_RGB,
		RST_RGB      => RST_RGB,
		BTN_UP       => BTN_UP,
		BTN_DOWN     => BTN_DOWN,
		SW_RGB       => SW_RGB,
		VALOR_SALIDA => S_VALOR_SALIDA
	);

	ROJO_OUT  <= S_VALOR_SALIDA.ROJO;
	VERDE_OUT <= S_VALOR_SALIDA.VERDE;
	AZUL_OUT  <= S_VALOR_SALIDA.AZUL;

	-- CLOCK
	CLK_RGB <= NOT CLK_RGB AFTER TBPERIOD/2 WHEN SIM_END = '0' ELSE '0';

	-- ESTÍMULOS
	STIMULI : PROCESS
	BEGIN
		-- RESET INICIAL
		RST_RGB <= '1';
		WAIT FOR 2*TBPERIOD;
		RST_RGB <= '0';
		WAIT FOR TBPERIOD;

		-- ================================
		-- 1. R=2, G=3, B=4
		-- ================================
		SW_RGB <= ROJO_SW;
		FOR I IN 1 TO 2 LOOP
			BTN_UP <= '1';
			WAIT FOR TBPERIOD;
			BTN_UP <= '0';
			WAIT FOR TBPERIOD;
		END LOOP;

		SW_RGB <= VERDE_SW;
		FOR I IN 1 TO 3 LOOP
			BTN_UP <= '1';
			WAIT FOR TBPERIOD;
			BTN_UP <= '0';
			WAIT FOR TBPERIOD;
		END LOOP;

		SW_RGB <= AZUL_SW;
		FOR I IN 1 TO 4 LOOP
			BTN_UP <= '1';
			WAIT FOR TBPERIOD;
			BTN_UP <= '0';
			WAIT FOR TBPERIOD;
		END LOOP;

		-- ================================
		-- 2. RESET
		-- ================================
		RST_RGB <= '1';
		WAIT FOR 2*TBPERIOD;
		RST_RGB <= '0';
		WAIT FOR TBPERIOD;

		-- ================================
		-- 3. ROJO A 15
		-- ================================
		SW_RGB <= ROJO_SW;
		FOR I IN 1 TO 15 LOOP
			BTN_UP <= '1';
			WAIT FOR TBPERIOD;
			BTN_UP <= '0';
			WAIT FOR TBPERIOD;
		END LOOP;

		-- INTENTO SUBIR MÁS
		BTN_UP <= '1';
		WAIT FOR TBPERIOD;
		BTN_UP <= '0';

		-- ================================
		-- 4. ROJO A 0
		-- ================================
		FOR I IN 1 TO 15 LOOP
			BTN_DOWN <= '1';
			WAIT FOR TBPERIOD;
			BTN_DOWN <= '0';
			WAIT FOR TBPERIOD;
		END LOOP;

		-- INTENTO BAJAR MÁS
		BTN_DOWN <= '1';
		WAIT FOR TBPERIOD;
		BTN_DOWN <= '0';

		WAIT FOR 10*TBPERIOD;
		SIM_END <= '1';

		ASSERT FALSE REPORT "SIMULACION FINALIZADA OK" SEVERITY NOTE;
		WAIT;
	END PROCESS;

END TB;
