-- TB PARA RGB_CONTROLADOR CON 8 BITS

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

-- CARGAMOS EL PAQUETE CON EL RECORD DE 8 BITS
USE WORK.PKG_RGB_TYPES.ALL;

ENTITY TB_RGB_CONTROLADOR IS
END TB_RGB_CONTROLADOR;

ARCHITECTURE TB OF TB_RGB_CONTROLADOR IS

	-- CONSTANTES DE TIEMPO Y CONFIGURACIÓN
	CONSTANT TBPERIOD : TIME := 100 NS;

	CONSTANT ROJO_SW : STD_LOGIC_VECTOR(3 DOWNTO 0) := "0100"; -- BIT 2
	CONSTANT VERDE_SW : STD_LOGIC_VECTOR(3 DOWNTO 0) := "0010"; -- BIT 1
	CONSTANT AZUL_SW : STD_LOGIC_VECTOR(3 DOWNTO 0) := "0001"; -- BIT 0

	-- DECLARACIÓN DEL COMPONENTE
	COMPONENT RGB_CONTROLADOR
		PORT (
			CLK_RGB : IN  STD_LOGIC;
			RST_RGB : IN  STD_LOGIC;
			BTN_UP : IN  STD_LOGIC;
			BTN_DOWN : IN  STD_LOGIC;
			SW_RGB : IN  STD_LOGIC_VECTOR (3 DOWNTO 0);
			VALOR_SALIDA : OUT T_COLORES_RGB
		);
	END COMPONENT;

	-- SEÑALES INTERNAS
	SIGNAL CLK_RGB : STD_LOGIC := '0';
	SIGNAL RST_RGB : STD_LOGIC := '0';
	SIGNAL BTN_UP : STD_LOGIC := '0';
	SIGNAL BTN_DOWN : STD_LOGIC := '0';
	SIGNAL SW_RGB : STD_LOGIC_VECTOR (3 DOWNTO 0) := "0000";
	SIGNAL SIM_END : STD_LOGIC := '0';

	-- SEÑAL RECORD Y CABLES DE 8 BITS PARA LA GRÁFICA
	SIGNAL S_VALOR_SALIDA : T_COLORES_RGB;
	SIGNAL ROJO_OUT : STD_LOGIC_VECTOR(7 DOWNTO 0); -- CAMBIADO A 8 BITS
	SIGNAL VERDE_OUT : STD_LOGIC_VECTOR(7 DOWNTO 0); -- CAMBIADO A 8 BITS
	SIGNAL AZUL_OUT : STD_LOGIC_VECTOR(7 DOWNTO 0); -- CAMBIADO A 8 BITS

BEGIN

	-- INSTANCIAMOS EL CONTROLADOR
	DUT : RGB_CONTROLADOR
	PORT MAP (
		CLK_RGB => CLK_RGB,
		RST_RGB => RST_RGB,
		BTN_UP => BTN_UP,
		BTN_DOWN => BTN_DOWN,
		SW_RGB => SW_RGB,
		VALOR_SALIDA => S_VALOR_SALIDA
	);

	-- DESEMPAQUETAMOS EL RECORD
	ROJO_OUT <= S_VALOR_SALIDA.ROJO;
	VERDE_OUT <= S_VALOR_SALIDA.VERDE;
	AZUL_OUT <= S_VALOR_SALIDA.AZUL;

	-- GENERADOR DE RELOJ
	CLK_RGB <= NOT CLK_RGB AFTER TBPERIOD/2 WHEN SIM_END = '0' ELSE '0';

	-- PROCESO DE ESTÍMULOS
	STIMULI : PROCESS
	BEGIN
		-- RESET INICIAL (LIMPIEZA)
		RST_RGB <= '1';
		WAIT FOR 2*TBPERIOD;
		RST_RGB <= '0';
		WAIT FOR TBPERIOD;

		-- 1. SUBIDAS:
		-- ROJO A 3
		SW_RGB <= ROJO_SW;
		FOR I IN 1 TO 3 LOOP
			BTN_UP <= '1';
			WAIT FOR TBPERIOD;
			BTN_UP <= '0';
			WAIT FOR TBPERIOD;
		END LOOP;

		-- AZUL A 2
		SW_RGB <= AZUL_SW;
		FOR I IN 1 TO 2 LOOP
			BTN_UP <= '1';
			WAIT FOR TBPERIOD;
			BTN_UP <= '0';
			WAIT FOR TBPERIOD;
		END LOOP;

		-- VERDE SE QUEDA EN 0 (NO TOCAMOS BTN_UP CON VERDE_SW)
		SW_RGB <= VERDE_SW;
		WAIT FOR 2*TBPERIOD;

		-- 2. BOTÓN DE RESET
		RST_RGB <= '1';
		WAIT FOR 2*TBPERIOD;
		RST_RGB <= '0';
		WAIT FOR 2*TBPERIOD;

		-- 3. SEGURIDAD MIN: BAJAR POR DEBAJO DE 0
		-- SI FUNCIONA LA MIN, FUNCIONA LA MAX
		SW_RGB <= ROJO_SW; -- SELECCIONAMOS ROJO (QUE ESTÁ EN 0 TRAS EL RESET)
		
		-- INTENTAMOS BAJAR 5 VECES MÁS
		FOR I IN 1 TO 5 LOOP
			BTN_DOWN <= '1';
			WAIT FOR TBPERIOD;
			BTN_DOWN <= '0';
			WAIT FOR TBPERIOD;
		END LOOP;
		-- ROJO_OUT DEBE SEGUIR SIENDO "00000000" (0 EN 8 BITS)

		-- FINALIZAMOS
		WAIT FOR 10*TBPERIOD;
		ASSERT FALSE REPORT "SIMULACION DE 8 BITS FINALIZADA OK" SEVERITY NOTE;
		SIM_END <= '1';
		WAIT;
	END PROCESS;

END TB;