LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

PACKAGE PKG_RGB_TYPES IS
	TYPE T_COLORES_RGB IS RECORD
		ROJO : STD_LOGIC_VECTOR(3 DOWNTO 0);
		VERDE : STD_LOGIC_VECTOR(3 DOWNTO 0);
		AZUL : STD_LOGIC_VECTOR(3 DOWNTO 0);
	END RECORD;
END PACKAGE PKG_RGB_TYPES;

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.PKG_RGB_TYPES.ALL;

ENTITY RGB_CONTROLADOR IS
	PORT (
		CLK_RGB : IN  STD_LOGIC;
		RST_RGB : IN  STD_LOGIC; -- RESET ACTIVO A NIVEL ALTO ('1')
		
		-- ENTRADAS
		BTN_UP, BTN_DOWN : IN  STD_LOGIC; 
		SW_RGB : IN  STD_LOGIC_VECTOR (3 DOWNTO 0); -- ROJO, VERDE, AZUL
		
		-- SALIDAS
		VALOR_SALIDA : OUT T_COLORES_RGB
	);
END RGB_CONTROLADOR;

ARCHITECTURE BEHAVIORAL OF RGB_CONTROLADOR IS

	-- DEFINICION DE LOS ESTADOS
	TYPE ESTADOS_T IS (S_REPOSO, S_SUBIR, S_BAJAR);
	SIGNAL ESTADO_ACTUAL : ESTADOS_T;
	SIGNAL ESTADO_SIGUIENTE : ESTADOS_T;

	-- REGISTROS INTERNOS
	SIGNAL R_REG : UNSIGNED(3 DOWNTO 0) := (OTHERS => '0');
	SIGNAL G_REG : UNSIGNED(3 DOWNTO 0) := (OTHERS => '0');
	SIGNAL B_REG : UNSIGNED(3 DOWNTO 0) := (OTHERS => '0');

BEGIN

END BEHAVIORAL;